
services:
  stremio-trakt-addon:
    image: reddravenn/stremio-trakt-addon
    container_name: stremio-trakt-addon
    expose:
      - 7000
    environment:
      PORT: 7000
      BASE_URL: https://${STREMIO_TRAKT_ADDON_HOSTNAME?}
      DB_USER: postgres
      DB_HOST: stremio-trakt-addon_postgres
      DB_NAME: stremio_trakt_db
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_MAX_CONNECTIONS: 20
      DB_IDLE_TIMEOUT: 30000
      DB_CONNECTION_TIMEOUT: 2000
      REDIS_HOST: stremio-trakt-addon_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID?}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET?}
      TMDB_CACHE_DURATION: 1d
      TRAKT_CACHE_DURATION: 1d
      TRAKT_HISTORY_FETCH_INTERVAL: 1d
      LOG_LEVEL: info
      LOG_INTERVAL_DELETION: 3d
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      stremio-trakt-addon_postgres:
        condition: service_healthy
      stremio-trakt-addon_redis:
        condition: service_healthy
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-trakt-addon/cache:/usr/src/app/cache
      - ${DOCKER_DATA_DIR}/stremio-trakt-addon/log:/usr/src/app/log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ravenn-trakt.rule=Host(`${STREMIO_TRAKT_ADDON_HOSTNAME?}`)"
      - "traefik.http.routers.ravenn-trakt.entrypoints=websecure"
      - "traefik.http.routers.ravenn-trakt.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ravenn-trakt.middlewares=authelia@docker"
    profiles:
      - stremio-trakt-addon
      - stremio
      - all

  stremio-trakt-addon_postgres:
    container_name: stremio-trakt-addon_postgres
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: stremio_trakt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${DOCKER_DATA_DIR}/stremio-trakt-addon/db:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stremio_trakt_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    profiles:
      - stremio-trakt-addon
      - stremio
      - all

  stremio-trakt-addon_redis:
    container_name: stremio-trakt-addon_redis
    image: redis:6
    restart: unless-stopped
    expose:
      - 6379 
    volumes:
      -  ${DOCKER_DATA_DIR}/stremio-trakt-addon/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - stremio-trakt-addon
      - stremio
      - all
